server:
  port: 8080
spring:
  datasource:
    username: rseofpdpsnjdtt
#    username: postgres
#    password: 911368169umid
    password: 4c20682f24092f443178ac6d3af2071836521776816515a34cfd3123c64fda6e
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/fastfood_api
    url: postgres://rseofpdpsnjdtt:4c20682f24092f443178ac6d3af2071836521776816515a34cfd3123c64fda6e@ec2-176-34-211-0.eu-west-1.compute.amazonaws.com:5432/d1jbfc1iroeis9
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      mode: ALWAYS
  mvc:
    servlet:
      path: /api
  servlet:
    multipart:
      max-file-size: 10MB
  application:
    name: ADMIN
debug: true

