server:
  port: 8080
spring:
  datasource:
    username: postgres
    password: 911368169umid
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fastfood_api
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      mode: ALWAYS
  mvc:
    servlet:
      path: /api
  servlet:
    multipart:
      max-file-size: 10MB
  profiles:
    active: prod
debug: true
app:
  auth:
    apikey:
      key: 9c65d6e78bc8540c511dbbfcdcd270fb
    secret: 9c65d6e78bc8540c511dbbfcdcd270fb
    token:
      type: Bearer
      cookieName: token
    header:
      key: Authorization
logging:
  level:
    org:
      springframework:
        boot: INFO
