server:
  port: 8080
spring:
  datasource:
    username: postgres
    password: 911368169umid
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fastfood_api
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      mode: ALWAYS
  mvc:
    servlet:
      path: /api
  servlet:
    multipart:
      max-file-size: 10MB
  application:
    name: ADMIN
debug: true

