GET http://localhost:8080/api/employee/1
Accept: application/json


###
GET http://localhost:8080/api/product
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiIxIiwiaWF0IjoxNjUzNTY0MTQ0LCJleHAiOjE2NTM1NzEzNDQsImlzcyI6IkF1dGggc2VydmljZSIsInVzZXJfaWQiOjEsInVzZXJfbmFtZSI6IlRvamlib3lldiBVbWlkam9uIiwidXNlcl9udW1iZXIiOiIrOTk4OTkwNDcyNDM2In0.mOCvxT2LdNugneaNPwzmNK3bPcGcHDzoL7N_sTMb2tpDyuNkmBWnNCY0baJarCuSJ78D-hozZTSsR8Yg9I82zw

###
POST http://localhost:8080/api/auth/token/get
Content-Type: application/json

{
  "login": "+998990472436",
  "password": "1234"
}

###

GET http://localhost:8080/api/auth/token/check
Accept: application/json
#Authorization: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiIxIiwiaWF0IjoxNjUyODgwMDA5LCJleHAiOjE2NTI4ODcyMDksImlzcyI6IkF1dGggc2VydmljZSIsInVzZXJfaWQiOjEsInVzZXJfbmFtZSI6IlRvamlib3lldiBVbWlkam9uIiwidXNlcl9udW1iZXIiOiIrOTk4OTkwNDcyNDM2In0.1ArMhQoEE5qw7HarV0QoqzLLn6h2Xc5Mgd2EVry0I183SGcw4B-ogIxpPBqJWnuMrQUVhhOmI5y09EFGwDNjDg
Cookie: token=eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiIxIiwiaWF0IjoxNjUyODgwMDA5LCJleHAiOjE2NTI4ODcyMDksImlzcyI6IkF1dGggc2VydmljZSIsInVzZXJfaWQiOjEsInVzZXJfbmFtZSI6IlRvamlib3lldiBVbWlkam9uIiwidXNlcl9udW1iZXIiOiIrOTk4OTkwNDcyNDM2In0.1ArMhQoEE5qw7HarV0QoqzLLn6h2Xc5Mgd2EVry0I183SGcw4B-ogIxpPBqJWnuMrQUVhhOmI5y09EFGwDNjDg




